site_name: worksheet
site_description: Worksheet for Teachers
repo_url: https://github.com/hoetaek/tdesk_backend
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/hoetaek">hoetaek</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
