# Generated by Django 4.1 on 2022-09-09 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wordsearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(choices=[('EASY', '쉬움'), ('NORMAL', '보통'), ('DIFFICULT', '어려움')], default='EASY', max_length=10)),
                ('is_scramble', models.BooleanField()),
                ('is_uppercase', models.BooleanField()),
                ('lang', models.CharField(choices=[('KR', '한글'), ('EN', '영어')], default='KR', max_length=2)),
                ('words', models.JSONField()),
            ],
        ),
    ]
